# Generated by Django 2.2 on 2019-07-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('Angry', models.IntegerField(default=0)),
                ('Disgust', models.IntegerField(default=0)),
                ('Fear', models.IntegerField(default=0)),
                ('Happy', models.IntegerField(default=0)),
                ('Sad', models.IntegerField(default=0)),
                ('Surprise', models.IntegerField(default=0)),
                ('Neutral', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=1200)),
                ('youtubeUrl', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=20)),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
