# Generated by Django 2.1.7 on 2019-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=1200)),
                ('youtubeUrl', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=20)),
            ],
        ),
    ]
