# Generated by Django 2.2 on 2019-07-31 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0002_videorecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiondata',
            name='vid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='livePage.VideoRecord'),
        ),
    ]
