# Generated by Django 2.1.7 on 2019-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0002_remove_usersetting_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='introduction',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='nickName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='youtubeUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
