# Generated by Django 2.1.7 on 2019-07-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0002_usersetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
