# Generated by Django 2.2 on 2019-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0003_auto_20190723_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiondata',
            name='time',
            field=models.TimeField(default='11:01:00'),
            preserve_default=False,
        ),
    ]
