# Generated by Django 2.1.7 on 2019-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
