# Generated by Django 2.2 on 2019-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0006_chatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='isLive',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
