# Generated by Django 2.1.7 on 2019-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0008_auto_20190918_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='date',
            new_name='nDate',
        ),
        migrations.RenameField(
            model_name='chatrecord',
            old_name='time',
            new_name='nTime',
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='category',
            field=models.CharField(default='Unknown', max_length=20, null=True),
        ),
    ]
