# Generated by Django 2.2 on 2019-10-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0009_auto_20190929_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='category',
            field=models.CharField(default='聊天', max_length=20, null=True),
        ),
    ]
