# Generated by Django 2.2 on 2019-10-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livePage', '0010_auto_20191013_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiondata',
            name='time',
            field=models.CharField(max_length=12),
        ),
    ]
